# Predefined trips for the departure board.
# Each trip appears as a tab on the page.
#
# Structure:
#   trip > routes > [transfer] > final_arrival_stop
#
# Times (transfer_time, final_walk_time) are in seconds.

# GTFS Departure Service API base URL
gtfs_api_url: "http://192.168.4.225:8074"
port: "3002"

trips:
  - name: "Home → Chippo"
    routes:
      - departure_stop_id: "206827"
        departure_name: "Middle Cove"
        transfer_arrival_stop_id: "2060116"
        transfer_time: 270
        transfer_departure_stop_id: "2060115"
        transfer_name: "Victoria Cross"
        final_arrival_stop: "2000467"
        final_walk_time: 720
        arrival_name: "Central"
      - departure_stop_id: "206827"
        departure_name: "Middle Cove"
        transfer_arrival_stop_id: "200096"
        transfer_time: 90
        transfer_departure_stop_id: "2000453"
        transfer_name: "City"
        final_arrival_stop: "2000443"
        final_walk_time: 720
        arrival_name: "Chinatown"
      - departure_stop_id: "206829"
        departure_name: "Castle Crag (EVW)"
        leg_1_services: 
        - "260"
        transfer_arrival_stop_id: "2060116"
        transfer_time: 270
        transfer_departure_stop_id: "2060115"
        transfer_name: "Victoria Cross"
        final_arrival_stop: "2060115"
        final_walk_time: 720
        arrival_name: "Central"
      - departure_stop_id: "206841"
        departure_name: "Castle Crag (Edinburgh Rd)"
        transfer_arrival_stop_id: "2060116"
        transfer_time: 270
        transfer_departure_stop_id: "2060115"
        transfer_name: "Victoria Cross"
        final_arrival_stop: "2060115"
        final_walk_time: 720
        arrival_name: "Central"

  - name: "Chippo → Home"
    routes:
      - departure_stop_id: "2000466"
        departure_name: "Central"
        transfer_arrival_stop_id: "2060114"
        transfer_time: 270
        transfer_departure_stop_id: "206083"
        transfer_name: "Victoria Cross"
        final_arrival_stop: "206846"
        final_walk_time: 240
        arrival_name: "Middle Cove"
      - departure_stop_id: "2000466"
        departure_name: "Central"
        transfer_arrival_stop_id: "2060114"
        transfer_time: 270
        transfer_departure_stop_id: "206083"
        transfer_name: "Victoria Cross"
        leg_2_services: 
        - "260"
        final_arrival_stop: "206844"
        final_walk_time: 840
        arrival_name: "Castle Crag"
      - departure_stop_id: "2000466"
        departure_name: "Central"
        transfer_arrival_stop_id: "2060114"
        transfer_time: 270
        transfer_departure_stop_id: "206083"
        transfer_name: "Victoria Cross"
        final_arrival_stop: "22068305"
        final_walk_time: 840
        arrival_name: "Castle Crag"
      - departure_stop_id: "2000444"
        departure_name: "Chinatown"
        transfer_arrival_stop_id: "2000452"
        transfer_time: 30
        transfer_departure_stop_id: "2000417"
        transfer_name: "Bridge St"
        final_arrival_stop: "206846"
        final_walk_time: 720
        arrival_name: "Middle Cove"